Repository ucsb-cs156-w22/team04-w22-6pm-courses, pull requests merged in 2022-03, with the labels that each got.

#25 Jl add load subjects
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminLoadSubjectsPage.js
  frontend/src/stories/pages/AdminLoadSubjectsPage/AdminLoadSubjectsPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/AdminLoadSubjectsPage.test.js
  frontend/src/tests/pages/AdminUsersPage.test.js
Labels: w22-6pm-2, 5

#24 Implement Curriculum Service and Controller for advanced course search
  src/main/java/edu/ucsb/cs156/example/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/example/documents/CourseSearchParams.java
  src/main/java/edu/ucsb/cs156/example/services/UCSBCurriculumService.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/example/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/example/services/UCSBCurriculumServiceTest.java
Labels: w22-6pm-1

#38 W22 6pm 2 nx personal schedule place holders
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesIndexPage.js
  frontend/src/stories/pages/PersonalSchedules/PersonalSchedulesCreatePage.stories.js
  frontend/src/stories/pages/PersonalSchedules/PersonalSchedulesIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
Labels: w22-6pm-2

#37 Courses Table Component and Tests
  frontend/src/fixtures/coursesFixtures.js
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/stories/components/Courses/CoursesTable.stories.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
Labels: w22-6pm-1

#36 Implement UCSBSubjectsService get function
  .env.SAMPLE
  pom.xml
  src/main/java/edu/ucsb/cs156/example/controllers/UCSBSubjectsController.java
  src/main/java/edu/ucsb/cs156/example/services/UCSBSubjectsService.java
  src/test/java/edu/ucsb/cs156/example/controllers/UCSBSubjectsControllerTests.java
  src/test/java/edu/ucsb/cs156/example/services/UCSBSubjectsServiceTests.java
Labels: w22-6pm-1

#26 Nx backend crud personal schedules
  src/main/java/edu/ucsb/cs156/example/controllers/PersonalSchedulesController.java
  src/main/java/edu/ucsb/cs156/example/entities/PersonalSchedule.java
  src/main/java/edu/ucsb/cs156/example/repositories/PersonalScheduleRepository.java
  src/test/java/edu/ucsb/cs156/example/controllers/PersonalSchedulesControllerTests.java
Labels: w22-6pm-2

#27 Added UCSB Subjects Table, alongside its tests and storybook component
  .gitignore
  frontend/src/fixtures/ucsbSubjectsFixtures.js
  frontend/src/main/components/UCSBSubjects/UCSBSubjectsTable.js
  frontend/src/main/utils/UCSBSubjectsUtils.js
  frontend/src/stories/components/UCSBSubjects/UCSBSubjectsTable.stories.js
  frontend/src/tests/components/UCSBSubjects/UCSBSubjectsTable.test.js
  frontend/src/tests/utils/UCSBSubjectsUtils.test.js
  src/main/java/edu/ucsb/cs156/example/entities/UCSBSubject.java
Labels: w22-6pm-2, Attn-Respond-to-CR

#43 Add Subject Selector Component
  frontend/src/fixtures/subjectFixtures.js
  frontend/src/main/components/CourseSearch/SubjectSelector.js
  frontend/src/main/utils/sortHelper.js
  frontend/src/stories/components/CourseSearch/SubjectSelector.stories.js
  frontend/src/tests/components/CourseSearch/SubjectSelector.test.js
  frontend/src/tests/utils/sortHelper.test.js
Labels: w22-6pm-1, Merge Candidate

#45 W22 6pm 2 nx personal schedule place holders admins
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminPersonalSchedules/AdminPersonalSchedulesIndexPage.js
  frontend/src/stories/pages/AdminPersonalSchedules/AdminPersonalSchedulesIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/AdminPersonalSchedules/AdminPersonalSchedulesIndexPage.test.js
Labels: w22-6pm-2

#50 W22 6pm 2 nx personal schedule table admins
  frontend/src/fixtures/adminPersonalSchedulesFixtures.js
  frontend/src/main/components/AdminPersonalSchedules/AdminPersonalSchedulesTable.js
  frontend/src/stories/components/AdminPersonalSchedules/AdminPersonalSchedulesTable.stories.js
  frontend/src/tests/components/AdminPersonalSchedules/AdminPersonalSchedulesTable.test.js
Labels: w22-6pm-2, 10

#39 Ja personal schedule form
  frontend/src/fixtures/personalSchedulesFixtures.js
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/stories/components/PersonalSchedules/PersonalScheduleForm.stories.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
Labels: w22-6pm-2, 10

#28 Tc course search form
  frontend/src/App.js
  frontend/src/fixtures/levelsFixtures.js
  frontend/src/fixtures/subjectFixtures.js
  frontend/src/index.css
  frontend/src/main/components/CourseSearch/CourseSearchForm.js
  frontend/src/main/components/CourseSearch/LevelSelector.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/CourseSearchPage.js
  frontend/src/main/utils/levelsUtils_NoStryker.js
  frontend/src/stories/components/CourseSearch/CourseSearchForm.stories.js
  frontend/src/stories/components/CourseSearch/LevelSelector.stories.js
  frontend/src/stories/pages/CourseSearch/CourseSearchPage.stories.js
  frontend/src/tests/components/CourseSearch/CourseSearchForm.test.js
  frontend/src/tests/components/CourseSearch/LevelSelector.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/CourseSearchPage.test.js
Labels: w22-6pm-1, Attn-needs peer CR

#40 W22 6pm 2 zl personal schedules table
  frontend/src/fixtures/personalSchedulesFixtures.js
  frontend/src/main/components/PersonalSchedules/PersonalSchedulesTable.js
  frontend/src/stories/components/PersonalSchedules/PersonalSchedulesTable.stories.js
  frontend/src/tests/components/PersonalSchedules/PersonalSchedulesTable.test.js
Labels: w22-6pm-2, Merge Candidate

#57 nx - added create page for PersonalSchedules users
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
Labels: w22-6pm-2

#58 nx - fixed admin nav bar navigating to the correct pages
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminLoadSubjectsPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: w22-6pm-2, 5
